### PR TITLE
Fix display content when employee list empty

### LINKED ISSUE #157: [PE-D] UI of an employee remains after clearing
I think clearing the app should clear all traces of records, and it could be better for the UI right panel to also clear the employee info.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zhuoyang125/ped#5

### LINKED ISSUE #175: [PE-D] After `clear` the view pane still displays a contact which no longer exists
-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: marcuschj/ped#13

### PR DESCRIPTION
**Pull request by 1waykiat**
Added overlay display on top of InfoPanel when employee list becomes empty due to `clear` and `delete` commands.

Also edited `delete` command to switch to viewing the first person in the employee list if list is not empty.

Resolves #157 and resolves #175

### CODE REVIEW

File: src/main/java/seedu/address/ui/InfoPanel.java [hunk 1]
```diff
@@ -51,49 +61,80 @@
...
+
         updateInfoPanel(p.get());
         p.addListener((x, y, z) -> {
             updateInfoPanel(z);
             System.out.println(y);
         });
     }
 
+    /**
+     * Removes the overlay on top of the InfoPanel
```
Comment (szelongq) [inline src/main/java/seedu/address/ui/InfoPanel.java:85]: Just a suggestion, but maybe it might be better to specify what the overlay is in the comments? Such as how it is used to display a message above the employee details or something like that?

**Review by szelongq — COMMENTED** [review]
LGTM! Just a small suggestion if you're ok with it!

File: src/main/java/seedu/address/ui/InfoPanel.java (hunk 1 above)
Comment (1waykiat) [reply src/main/java/seedu/address/ui/InfoPanel.java]: Added further explanation on what the overlay has.

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 2]
```diff
@@ -45,8 +45,8 @@ public CommandResult execute(Model model) throws CommandException {
         if (model.isFilteredPersonListEmpty()) {
             // View blank
             model.setViewingPerson(null);
-        } else {
-            // Show first employee
+        } else if (personToDelete.equals(model.getViewingPerson().get())) {
```
Comment (szelongq) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java:48]: Just a suggestion, but since there is actually a method `Person.isSamePerson()`, maybe using that would be clearer?

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 3]
```diff
@@ -84,6 +84,10 @@ public CommandResult execute(Model model) throws CommandException {
             // Should not happen since "1" is a valid index, and import file must have at least 1 entry.
             throw new CommandException(e.getMessage());
         }
+
+        List<Person> importedList = model.getFilteredPersonList();
+        model.setViewingPerson(importedList.get(0));
```
Comment (szelongq) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:89]: Maybe this is not needed because a view command is called already in line 82?

**Review by szelongq — COMMENTED** [review]
Just another two more small nitpicks, otherwise LGTM!

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java (hunk 2 above)
Comment (1waykiat) [reply src/main/java/seedu/address/logic/commands/DeleteCommand.java:48]: Thanks, for some reason did not realise that method existed.

File: src/main/java/seedu/address/logic/commands/ImportCommand.java (hunk 3 above)
Comment (1waykiat) [reply src/main/java/seedu/address/logic/commands/ImportCommand.java:89]: Ah was blind and did not see. Thanks for catching this :)

**Comment by 1waykiat** [comment]
In addition to taking account your comments, I have also changed up the Observer implementation for InfoPanel

(🙏 ps for stacking so many different kind of updates here, probably should have opened up another branch )

File: src/main/java/seedu/address/model/person/ObservablePerson.java [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+    /**
+     * Adds any {@code UiObserver} to the list of observers to be updated when
+     * {@code personToView} is updated through {@code setPerson}.
+     */
+    public void addUiObserver(UiObserver observer) {
+        uiObserverList.add(observer);
+    }
+
+    /**
+     * Updates the {@code UiObservers} in the observer list with the current person to view.
```
Comment (szelongq) [inline src/main/java/seedu/address/model/person/ObservablePerson.java:44]: I think maybe there shouldn't be an 's' here as the `@code` refers to a class and `UiObserver` is the class name?

File: src/main/java/seedu/address/ui/InfoPanel.java [hunk 5]
```diff
@@ -68,17 +68,14 @@
...
 
         textOverlay.setText(LIST_EMPTY_MSG);
         textOverlay.setTextAlignment(TextAlignment.CENTER);
 
         updateInfoPanel(p.get());
-        p.addListener((x, y, z) -> {
-            updateInfoPanel(z);
-            System.out.println(y);
-        });
+        p.addUiObserver(this);
```
Comment (szelongq) [inline src/main/java/seedu/address/ui/InfoPanel.java:78]: Just a really small nitpick, but maybe it would be clearer to rename the parameter here to something clearer like 'viewingPerson'?

File: src/main/java/seedu/address/ui/InfoPanel.java [hunk 6]
```diff
@@ -68,17 +68,14 @@
      * Creates a {@code InfoPanel} with the given {@code Person}.
```
Comment (szelongq) [inline src/main/java/seedu/address/ui/InfoPanel.java:68]: Perhaps the header comment here could be updated with regards to how `ObservablePerson` is used?

**Review by szelongq — COMMENTED** [review]
LGTM! I like the new implementation of the Observer design pattern! Just a couple of nitpicks in terms of code quality.

File: src/main/java/seedu/address/model/person/ObservablePerson.java [hunk 7]
```diff
@@ -0,0 +1,51 @@
...
+
+/**
+ * Observable class for Person to use Observer pattern to update InfoPanel.
+ */
+public class ObservablePerson {
+    private Person personToView;
+    private ArrayList<UiObserver> uiObserverList = new ArrayList<>();
+
+    /**
+     * Initialises the ObservablePerson object with the person to be viewed.
```
[the remark this answers is not in the document]
Comment (1waykiat) [reply src/main/java/seedu/address/model/person/ObservablePerson.java:16]: Suggestion Taken!

File: src/main/java/seedu/address/model/person/ObservablePerson.java [hunk 8]
```diff
@@ -0,0 +1,51 @@
...
+    /**
+     * Sets the new person to be viewed in the ObservablePerson object,
+     * and updates the respective Ui components that are observing it.
+     */
+    public void setPerson(Person person) {
+        personToView = person;
+        updateUi();
+    }
+
+    public Person get() {
```
[the remark this answers is not in the document]
Comment (1waykiat) [reply src/main/java/seedu/address/model/person/ObservablePerson.java:31]: Suggestion Taken!

File: src/main/java/seedu/address/model/person/ObservablePerson.java (hunk 4 above)
Comment (1waykiat) [reply src/main/java/seedu/address/model/person/ObservablePerson.java:44]: Suggestion Taken!

File: src/main/java/seedu/address/ui/InfoPanel.java (hunk 6 above)
Comment (1waykiat) [reply src/main/java/seedu/address/ui/InfoPanel.java:68]: Suggestion Taken!

File: src/main/java/seedu/address/ui/InfoPanel.java (hunk 5 above)
Comment (1waykiat) [reply src/main/java/seedu/address/ui/InfoPanel.java:78]: Not really sure which parameter your referring to, but added comments to try to explain the line.

**Comment by 1waykiat** [comment]
With regards to the Optional suggestion, I feel that with the current implementation its redundant to change it to Optional, as either way we need to return a null back with the getPerson() method.

I tried utilising Optional in the ModelManager instead though.

**Review by szelongq — APPROVED** [review]
LGTM!
